name: shop_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_pro: ^0.0.13 #
  fluttertoast: ^3.0.3 # toast
  shared_preferences: ^0.5.1+1 #数据共享
  dio: ^2.1.0  #网络请求 
  # modal_progress_hud: ^0.1.3  # loading
  flutter_spinkit: "^3.1.0" # loading
  amap_base: ^0.3.5
  fluttery_seekbar: ^0.0.1
  # barcode_scan: ^0.0.4 # 二维码扫描
  flutter_screenutil: ^0.5.2 # 屏幕适配




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - images/bg.jpg
  - images/icon.png
  - images/01.png
  - images/02.png
  - images/03.png
  - images/sun.png
  - images/logo.png
  - images/nike_logo.jpg

  # 分类图片
  - images/cats/001.png
  - images/cats/002.png
  - images/cats/003.png
  - images/cats/004.png
  - images/cats/005.png
  - images/cats/006.png
  - images/cats/007.png
  - images/cats/008.png
  - images/cats/009.png
  - images/cats/010.png
  - images/cats/011.png
  - images/products/pro01.jpg
  - images/products/pro02.png
  - images/products/pro03.png
  - images/products/pro04.png
  - images/products/pro05.png
  - images/products/pro06.jpg
  # 地图相关图片
  - images/default_marker.png
  # 卡片图片
  - images/cards/01.png
  - images/cards/02.png
  - images/cards/03.png
  - images/cards/04.png
  # nike 图片
  - images/nike/shoes.png
  - images/nike/shoes02.png


  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
